<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New User</name>
   <tag></tag>
   <elementGuidId>a2822d09-29a8-49ff-a07d-14b62903c53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='newUser']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newUser</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>351acfd0-ac58-4086-b938-057c4df0ee29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newUser</value>
      <webElementGuid>b9053f25-139f-47d2-a627-0e2f5d113014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ecafbb3-24ba-463a-8f48-ee8c804aa246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>540aaa10-1801-4ecd-bd2f-aa15912220f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New User</value>
      <webElementGuid>ad9c0b47-e00f-4b74-ad35-8de3f5b093e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newUser&quot;)</value>
      <webElementGuid>7e14744c-9bd9-4d84-a850-141fe6513aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='newUser']</value>
      <webElementGuid>75a8410a-931c-48a2-81d4-a48608c6a19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='userForm']/div[4]/div[2]/button</value>
      <webElementGuid>a4289e3f-9324-4bda-8107-5d4e7003638a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b561dcbe-8a4f-48fc-aa94-666bf4599a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'newUser' and @type = 'button' and (text() = 'New User' or . = 'New User')]</value>
      <webElementGuid>a090db46-f60e-4c0c-887c-9a16781c6ab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
