<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_col-md-9 col-sm-12</name>
   <tag></tag>
   <elementGuidId>f22cc27b-c2a1-4f8d-ba60-db9c0b7c6cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userName-wrapper']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userName-wrapper > div.col-md-9.col-sm-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>156ea998-c545-46d3-a5eb-cb37594d642a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-9 col-sm-12</value>
      <webElementGuid>f22d50c4-a210-4875-bfcd-0268ce280e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName-wrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]</value>
      <webElementGuid>35f8bcbb-935a-4cf9-aa60-2a2145a0030a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userName-wrapper']/div[2]</value>
      <webElementGuid>df9399c4-7330-4dfa-8598-b5d3bdc02e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div[2]</value>
      <webElementGuid>38a3fd59-d303-4cf8-bc09-f72da2d4206a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
