<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go To Book Store</name>
   <tag></tag>
   <elementGuidId>4a24d414-ab7b-4f56-b034-258941f5d837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gotoStore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gotoStore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>183e8295-37f8-4d19-8f7e-ab480d872dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotoStore</value>
      <webElementGuid>b0c4b5cd-651c-446d-b0db-f97337ea0e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98806cae-5bbf-475d-963c-dee572ed6fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>095d7ef4-c63e-45ff-bae2-a0d38011f2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To Book Store</value>
      <webElementGuid>b856d288-df7e-4a72-8567-8b1dd5d6eca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotoStore&quot;)</value>
      <webElementGuid>087cefcb-a14c-4700-95c9-0a8c7c40539b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gotoStore']</value>
      <webElementGuid>373df197-6c98-4c6f-b227-48453f877084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[3]/div/button</value>
      <webElementGuid>4573d0dd-101d-4e91-9950-a31255912f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>c7b2387e-c863-4641-bc84-8d1ef38fd55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gotoStore' and @type = 'button' and (text() = 'Go To Book Store' or . = 'Go To Book Store')]</value>
      <webElementGuid>a297f876-1741-4dad-8b0c-ce35e69dfe7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
